import toast from 'react-hot-toast'
import { FileDown, FileText } from 'lucide-react'
import type { GeneratedSRS } from '../../types/index.ts'
import { srsApi } from '../../lib/api'

interface SRSExporterProps {
  document: GeneratedSRS
}

function toMarkdown(document: GeneratedSRS): string {
  const output: string[] = []
  output.push('# Software Requirements Specification')
  output.push(`## ${document.repoName}`)
  output.push(`**Version:** ${document.version} | **Date:** ${new Date(document.generatedAt).toLocaleString()} | **Generated by:** NDEX AI`)
  output.push('')
  output.push('---')
  output.push('')
  output.push('## Table of Contents')
  output.push('1. Introduction')
  output.push('2. Overall Description')
  output.push('3. Functional Requirements')
  output.push('4. Non-Functional Requirements')
  output.push('5. System Architecture')
  output.push('6. Data Models')
  output.push('7. API Endpoints')
  output.push('8. Testing Requirements')
  output.push('9. Glossary')
  output.push('')

  output.push('## 1. Introduction')
  output.push('### 1.1 Purpose')
  output.push(document.document.introduction.purpose)
  output.push('')
  output.push('### 1.2 Scope')
  output.push(document.document.introduction.scope)
  output.push('')
  output.push('### 1.3 Overview')
  output.push(document.document.introduction.overview)
  output.push('')

  output.push('## 2. Overall Description')
  output.push('### 2.1 Product Perspective')
  output.push(document.document.overallDescription.productPerspective)
  output.push('')
  output.push('### 2.2 Product Functions')
  document.document.overallDescription.productFunctions.forEach(fn => output.push(`- ${fn}`))
  output.push('')

  output.push('## 3. Functional Requirements')
  document.document.functionalRequirements.forEach(fr => {
    output.push(`### ${fr.id}: ${fr.title}`)
    output.push(`**Priority:** ${fr.priority}`)
    output.push(`**Description:** ${fr.description}`)
    output.push(`**Inputs:** ${fr.inputs.join(', ')}`)
    output.push(`**Outputs:** ${fr.outputs.join(', ')}`)
    output.push(`**Dependencies:** ${fr.dependencies.join(', ')}`)
    output.push('')
  })

  output.push('## 4. Non-Functional Requirements')
  document.document.nonFunctionalRequirements.forEach(nfr => {
    output.push(`### ${nfr.id} (${nfr.category})`)
    output.push(`**Description:** ${nfr.description}`)
    output.push(`**Metric:** ${nfr.metric}`)
    output.push(`**Rationale:** ${nfr.rationale}`)
    output.push('')
  })

  output.push('## 5. System Architecture')
  output.push(document.document.systemArchitecture.description)
  output.push('')

  output.push('## 6. Data Models')
  document.document.dataModels.forEach(model => {
    output.push(`### ${model.name}`)
    output.push(model.description)
    model.fields.forEach(field => {
      output.push(`- ${field.name} (${field.type}) required=${field.required}: ${field.description}`)
    })
    output.push('')
  })

  output.push('## 7. API Endpoints')
  document.document.apiEndpoints.forEach(endpoint => {
    output.push(`- **${endpoint.method} ${endpoint.path}**: ${endpoint.description}`)
  })
  output.push('')

  output.push('## 8. Testing Requirements')
  output.push(`- Unit Testing: ${document.document.testingRequirements.unitTesting}`)
  output.push(`- Integration Testing: ${document.document.testingRequirements.integrationTesting}`)
  output.push(`- E2E Testing: ${document.document.testingRequirements.e2eTesting}`)
  output.push(`- Performance Testing: ${document.document.testingRequirements.performanceTesting}`)
  output.push('')

  output.push('## 9. Glossary')
  document.document.glossary.forEach(item => output.push(`- **${item.term}**: ${item.definition}`))

  return output.join('\n')
}

function triggerDownload(content: BlobPart, fileName: string, mime: string): void {
  const blob = new Blob([content], { type: mime })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = fileName
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}

export default function SRSExporter({ document: srsDocument }: SRSExporterProps) {
  const exportToMarkdown = async (): Promise<void> => {
    try {
      const markdown = toMarkdown(srsDocument)
      const fileName = `${srsDocument.repoName.replace('/', '-')}-SRS-v${srsDocument.version}.md`
      triggerDownload(markdown, fileName, 'text/markdown;charset=utf-8')
      toast.success('SRS exported as Markdown')
    } catch {
      toast.error('Export failed — try again')
    }
  }

  const exportViaBackend = async (): Promise<void> => {
    try {
      const response = await srsApi.exportMarkdown(srsDocument.id)
      const fileName = `${srsDocument.repoName.replace('/', '-')}-SRS-v${srsDocument.version}.md`
      triggerDownload(response.data, fileName, 'text/markdown;charset=utf-8')
      toast.success('SRS exported as Markdown')
    } catch {
      await exportToMarkdown()
    }
  }

  const exportToPDF = (): void => {
    try {
      const style = window.document.createElement('style')
      style.setAttribute('media', 'print')
      style.innerHTML = `
        @page { margin: 18mm; }
        body { background: #ffffff !important; color: #000000 !important; }
        aside, header, button, .no-print { display: none !important; }
        .print-root { max-width: 100% !important; box-shadow: none !important; border: none !important; }
        .print-section { page-break-before: always; }
      `
      window.document.head.appendChild(style)
      window.print()
      window.document.head.removeChild(style)
      toast.success('Print dialog opened for PDF export')
    } catch {
      toast.error('Export failed — try again')
    }
  }

  return (
    <div style={{ display: 'flex', gap: 8 }}>
      <button
        type="button"
        onClick={() => void exportViaBackend()}
        style={{
          height: 32,
          padding: '0 12px',
          border: '1px solid var(--border-2)',
          borderRadius: 'var(--radius-md)',
          background: 'var(--bg-surface)',
          color: 'var(--text-2)',
          display: 'inline-flex',
          alignItems: 'center',
          gap: 6,
          cursor: 'pointer',
          fontSize: 12,
        }}
      >
        <FileText size={14} />
        Export MD
      </button>

      <button
        type="button"
        onClick={exportToPDF}
        style={{
          height: 32,
          padding: '0 12px',
          border: '1px solid var(--border-2)',
          borderRadius: 'var(--radius-md)',
          background: 'var(--bg-surface)',
          color: 'var(--text-2)',
          display: 'inline-flex',
          alignItems: 'center',
          gap: 6,
          cursor: 'pointer',
          fontSize: 12,
        }}
      >
        <FileDown size={14} />
        Export PDF
      </button>
    </div>
  )
}
